import logo from "./image/logo.png"
import shahin from "./image/sss.png"
import img1 from "./image/shopping.png"
import img2 from "./shofyecommerce.png"
import img3 from "./summer_sale.png"
import img4 from "./esproduct.png"
import people from "./image/peoplentech.png"
import progranning from "./image/company.png"
import habiganj from "./image/habiganj.jpg"
import pdf from "./image/shahin.pdf"
import productbd from "./ecommerceplantshop.png"
export { logo, shahin, img1, img2, img3, img4, pdf, people, progranning, habiganj, productbd }